---
apiVersion: v1
kind: Secret
metadata:
  name: apporders67-repo
  namespace: devhub
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-mad/apporders67-backend-gitops
